using ScreenRecorder.Core;

namespace ScreenRecorder.App;

public static class UiLabels
{
    public const string AppName = "ScreenRecorder";
    public const string Screenshot = "スクリーンショット";
    public const string Record = "録画";
    public const string FullDisplay = "ディスプレイ全体";
    public const string SelectRegion = "範囲を指定";
    public const string SelectWindow = "ウィンドウを指定";
    public const string PauseResume = "録画を一時停止/再開";
    public const string StopRecording = "録画を停止";
    public const string OpenImageFolder = "静止画の保存先を開く";
    public const string OpenVideoFolder = "動画の保存先を開く";
    public const string Settings = "設定...";
    public const string SettingsTitle = "ScreenRecorder の設定";
    public const string GeneralTab = "全般";
    public const string GeneralPreferences = "サインインと通知";
    public const string FilenameOptions = "ファイル名";
    public const string ApplicationTools = "アプリの管理";
    public const string StillImageTab = "静止画";
    public const string StillImageOptions = "撮影と保存";
    public const string VideoTab = "動画";
    public const string VideoImageOptions = "映像";
    public const string AudioOptions = "音声";
    public const string ShortcutsTab = "ショートカット";
    public const string ShortcutInstructions = "入力方法";
    public const string ShortcutAssignments = "操作ごとの割り当て";
    public const string StartWithWindows = "サインイン時に起動";
    public const string CheckForUpdatesAutomatically = "更新を自動で確認";
    public const string NotifyWhenSaved = "保存完了を通知";
    public const string PlayCaptureSound = "撮影時に効果音を鳴らす";
    public const string FileNameTemplate = "ファイル名のひな形";
    public const string OrganizeByMonth = "月ごとのフォルダーに分ける";
    public const string OpenLogsFolder = "ログのフォルダーを開く";
    public const string RestoreDefaults = "すべての設定を既定に戻す";
    public const string OpenLicense = "ライセンスを開く";
    public const string StillImageDirectory = "保存先";
    public const string ImageFormat = "形式";
    public const string JpegQuality = "JPEG の品質";
    public const string PngCompression = "PNG の圧縮";
    public const string CopyImageToClipboard = "クリップボードへコピー";
    public const string CaptureImageCursor = "カーソルを写す";
    public const string CaptureDelay = "撮影までの遅延";
    public const string AfterCaptureAction = "撮影後の動作";
    public const string VideoDirectory = "保存先";
    public const string FrameRate = "フレームレート";
    public const string VideoBitrate = "ビットレート";
    public const string CaptureVideoCursor = "カーソルを写す";
    public const string Countdown = "録画開始前のカウントダウン";
    public const string OutputScale = "出力の大きさ";
    public const string HighlightClicks = "クリック位置を強調する";
    public const string Encoder = "エンコーダ";
    public const string CaptureSystemAudio = "PC の音を収録";
    public const string CaptureMicrophone = "マイクを収録";
    public const string MicrophoneDevice = "マイクのデバイス";
    public const string AudioFormat = "音声形式";
    public const string AacBitrate = "AAC のビットレート";
    public const string Mp3Bitrate = "MP3 のビットレート";
    public const string DefaultDevice = "既定のデバイス";
    public const string SavedMicrophoneDevice = "保存済みのデバイス";
    public const string Jpeg = "JPEG";
    public const string Png = "PNG";
    public const string PngFast = "速い";
    public const string PngStandard = "標準";
    public const string PngSmallest = "最小サイズ";
    public const string CaptureAfterNone = "何もしない";
    public const string CaptureAfterOpenFile = "既定のアプリで開く";
    public const string CaptureAfterOpenFolder = "保存先を開く";
    public const string Aac = "AAC";
    public const string Mp3 = "MP3";
    public const string EncoderAutomatic = "自動";
    public const string EncoderSoftwareOnly = "ソフトウェアのみ";
    public const string None = "なし";
    public const string Browse = "参照...";
    public const string Ok = "OK";
    public const string Cancel = "キャンセル";
    public const string ShortcutUnassigned = "割り当てなし";
    public const string ShortcutDuplicate = "ほかの操作と重複しています。キーを変更してください。";
    public const string ShortcutInvalid = "キーの表記を読み取れません。別のキーを入力してください。";
    public const string ShortcutStatusUnavailable = "登録できません";
    public const string ShortcutStatusDuplicate = "重複しています";
    public const string ShortcutRegistrationFailed = "このキーを登録できませんでした。ほかのアプリが使用している可能性があります。";
    public const string PrintScreenSnippingHint = "Windows の「Print Screen キーを使用して画面キャプチャを開く」が有効なため、PrtSc を登録できません。";
    public const string OpenKeyboardSettings = "Windows のキーボード設定を開く";
    public const string StartupHotkeyFailureTitle = "ショートカットを登録できませんでした";
    public const string StartupHotkeyFailureBody = "一部のショートカットを登録できませんでした。設定画面で状態を確認してください。";
    public const string SettingsSaveFailed = "設定を保存できませんでした。入力内容を確認して、もう一度お試しください。";
    public const string RestoreDefaultsConfirmation = "すべての設定を既定値に戻します。変更は OK を押すまで保存されません。続けますか？";
    public const string RestoreDefaultsTitle = "設定を既定に戻す";
    public const string NotImplemented = "この機能はまだ利用できません。";
    public const string FolderOpenFailed = "フォルダーを開けませんでした: {0}";
    public const string FolderPickerTitle = "保存先のフォルダーを選択";
    public const string SettingsApplyFailed = "設定は保存しましたが、自動起動の登録に失敗しました。";
    public const string SettingsApplyHotkeyFailed = "設定は保存しましたが、一部のショートカットを登録できませんでした。";
    public const string SettingsApplyPrintScreenFailed = "Windows の画面キャプチャ設定が有効なため、PrtSc を登録できませんでした。";
    public const string NoShortcutFailures = "登録に失敗したショートカットはありません。";
    public const string ShortcutRegistrationProblem = "登録できないショートカットがあります。";
    public const string ShortcutEntryHelp = "入力欄を選んでキーを押すと登録します。Backspace または Delete で割り当てを解除します。";
    public const string ShortcutRegistrationStatus = "登録状態";
    public const string ShortcutColumnAction = "操作";
    public const string ShortcutColumnKey = "キー";
    public const string ShortcutColumnStatus = "状態";
    public const string FilenameTemplateHelp = "{date} は日付、{time} は時刻、{mode} は撮影方法、{window} はウィンドウ名に置き換わります。";
    public const string CaptureDelayHelp = "範囲またはウィンドウを選んだ後、撮影まで待つ時間です。";
    public const string DirectoryRequired = "保存先のフォルダーを指定してください。";
    public const string SettingsValuesInvalid = "設定値を確認してください。";
    public const string LicenseOpenFailed = "ライセンスを開けませんでした。";
    public const string KeyboardSettingsOpenFailed = "Windows のキーボード設定を開けませんでした。";
    public const string Seconds3 = "3 秒";
    public const string Seconds5 = "5 秒";
    public const string Seconds10 = "10 秒";
    public const string FifteenFramesPerSecond = "15 fps";
    public const string TwentyFourFramesPerSecond = "24 fps";
    public const string ThirtyFramesPerSecond = "30 fps";
    public const string SixtyFramesPerSecond = "60 fps";
    public const string MegabitsPerSecond = "Mbps";
    public const string JpegQualityRange = "1–100";
    public static string KilobitsPerSecond(int value) => $"{value} kbps";
    public const string Manual = "マニュアル";
    public const string CheckForUpdates = "更新を確認";
    public const string Exit = "終了";

    public static string ShortcutActionName(RecorderAction action) => action switch
    {
        RecorderAction.ScreenshotRegion => $"{Screenshot}: {SelectRegion}",
        RecorderAction.ScreenshotFullScreen => $"{Screenshot}: {FullDisplay}",
        RecorderAction.ScreenshotWindow => $"{Screenshot}: {SelectWindow}",
        RecorderAction.RecordingRegion => $"{Record}: {SelectRegion}",
        RecorderAction.RecordingFullScreen => $"{Record}: {FullDisplay}",
        RecorderAction.RecordingWindow => $"{Record}: {SelectWindow}",
        RecorderAction.PauseResume => PauseResume,
        _ => StopRecording
    };
}
